{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "transaction-api.serviceAccountName" . }}
  labels:
    {{- include "transaction-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
- name: {{ include "transaction-api.serviceAccountName" . }}-secret
{{- end }}